### PR TITLE
Make .np history output correct times

### PR DESCRIPTION
**Pull request by iandioch**
Because of timezone changes, this was the previous output of `.np history`:

```
17:50 Yeah Yeah Yeahs Heads Will Roll
17:47 Hooverphonic    Amalfi
17:44 Beth Ditto      Fire
17:41 DJ Shadow       Changeling II - Adrian Yo
17:33 Groove Armada   Inside My Mind (Blue Skie
```

But following is the correct output:

```
18:50 Yeah Yeah Yeahs Heads Will Roll
18:47 Hooverphonic    Amalfi
18:44 Beth Ditto      Fire
18:41 DJ Shadow       Changeling II - Adrian Yo
18:33 Groove Armada   Inside My Mind (Blue Skie
```

This PR fixes this issue by recognising the given time as UTC and converting the output time to IST.

### CODE REVIEW

**Comment by sentriz** [comment]
Hmmm the TZ should come from config.py probably

**Comment by iandioch** [comment]
You may indeedy be correct

**Comment by iandioch** [comment]
Have changed, PTAL

**Comment by sentriz** [comment]
👌👌👌 are you ready to merge?

**Comment by iandioch** [comment]
yea boiii

**Pull request merged**
