### PR TITLE
Add Telegram frontend

### PR DESCRIPTION
**Pull request by iandioch**
Missing images in thread history, but is usable

### CODE REVIEW

**Comment by devoxel** [comment]
Beautiful hack

**Comment by iandioch** [comment]
Valid use of copy and paste, leave me alone

**Comment by sentriz** [comment]
i'm okay with the code duplication if we plan on deleting the facebook part of steely >:)

what are we thinking

**Comment by iandioch** [comment]
deleting sounds good

**Comment by iandioch** [comment]
Cian's comment is good enough for me, delete the FB bit soon

**Pull request merged**
